### PR TITLE
Add ga_sent_at to prevent duplicates

### PR DESCRIPTION
**Pull request by barryvdh**
This prevents https://github.com/elgentos/magento2-serversideanalytics/issues/5 from happening, even if its fault lies outside this module.

If for any reason, an even is already sent, it should not happen again. Otherwise the order might be tracked twice.

### CODE REVIEW

**Comment by peterjaap** [comment]
@barryvdh great idea, but we don't like changing the core Magento database schema and certainly not adding columns to the `sales_order` table. When a store has many, many orders, the deployment (`bin/magento setup:upgrade` step) will take several minutes (up to an hour for a few of our clients) due to this change, causing unnecessary downtime.

Could you refactor this by adding a pivot table (`sales_order_ga` or something) with a foreign key to `sales_order.entity_id` and use that table to retrieve the `ga_sent_at` value?

**Comment by barryvdh** [comment]
Hmm, but this is exactly the same as the ga_user_id column? https://github.com/elgentos/magento2-serversideanalytics/blob/master/Setup/UpgradeSchema.php#L19-L29

**Comment by peterjaap** [comment]
@barryvdh yes, that exact commit was the main reason we now consider adding a column to Magento's schema a bad practice.

**Comment by barryvdh** [comment]
Okay I will see what I can do, but to be honest, this isn't a top priority for me so I have to see when I can get around this. I have this patch running in production already, just though it could be helpful to someone else.

**Comment by peterjaap** [comment]
@barryvdh I totally understand :) We'll just leave it here in case somebody else runs into this and is willing to pick this up :)

**Comment by peterjaap** [comment]
Here's another option; https://m.academy/blog/programmatically-add-column-magento-2-sales-order-database-table/

**Comment by WouterSteen** [comment]
@barryvdh we have implemented a pivot table and many refactors. Do you want to update this MR? Seems something we would still want? Al tough I'm being told that GA fixes this for you now?

**Pull request closed without merging**
