### PR TITLE
Changes for GA4 and removed UA

### PR DESCRIPTION
**Pull request by JoostWan**
- Removed code that was for the UA version of Google Analytics
- Fix the bug with the Cookie and GA version check
- Added session_id because it's needed to link the conversion to the correct session of the visitor. 
- The conversion comes into Google Analytics and is then displayed in reports as not linked to a session. You can see this as "Unassigned". To do so, the session_id is required, but it takes up to 48 hours for that data to be processed.

More info about the session_id with GA4 can be found here 

- https://trackingchef.com/google-analytics/how-to-add-session-id-to-ga4-measurement-protocol-events/
- https://www.simoahava.com/analytics/session-attribution-with-ga4-measurement-protocol/
- https://tagticians.com/solving-ga4s-session-issue-in-segment/

Can you check if it is working properly on your end as well?

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks!
I've installed this patch. I see session id is stored in the last few orders, but will have to wait after the weekend to see the results.

**Comment by JoostWan** [comment]
@barryvdh I think this is not possible at this moment because the limitations of the Measurement protocol for GA4. 

_Geographic information is only available via automatic collection from gtag, Google Tag Manager, or Google Analytics for Firebase._

_Device information is only available via automatic collection from gtag, Google Tag Manager, or Google Analytics for Firebase._

https://developers.google.com/analytics/devguides/collection/protocol/ga4

**Comment by WouterSteen** [comment]
@JoostWan Are you willing to refactor this module a bit so we dont have to add another column to the quote/order table?

**Comment by WouterSteen** [comment]
Obv I would fully understand if you dont want to :) haha

Really appriciate the your input here!

I want to test this on a client who is asking for this, but cant right now because this db is like 20gb with order data, so when i put this to production the site is going to be offline for a while :)

Here is an article on what needs to be done: https://m.academy/blog/programmatically-add-column-magento-2-sales-order-database-table/

Ill look in to this later next week. Cheers!

**Comment by WouterSteen** [comment]
Working on it now! Hope ill finish today

**Comment by WouterSteen** [comment]
Almost done!

**Comment by barryvdh** [comment]
Do you have this working properly with alle the data matched? As discussed on Slack, we seemed to be missing source data etc from the transactions, so it looked like it didn't properly match. But not so familiar with GA4. We switched to client-side for now.

**Comment by WouterSteen** [comment]
> Do you have this working properly with alle the data matched? As discussed on Slack, we seemed to be missing source data etc from the transactions, so it looked like it didn't properly match. But not so familiar with GA4. We switched to client-side for now.

In my new merge request this is working, as far as I could see. 

But no production env yet, because we have a small bug in the pivot table. My team will work on this, as I'm on holiday next few weeks.

**Comment by WouterSteen** [comment]
@barryvdh @JoostWan ive pushed version 1.1.1. This contains fixes for GA4. This is been released in production today.

@JoostWan thanks for creating this MR!

**Pull request closed without merging**
